services:
  dev:
    container_name: php
    build: .
    networks:
      - networkName
  neo4j:
    container_name: neo4j
    image: neo4j
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
    networks:
      - networkName 
networks:
  networkName:
    driver: bridge